### ISSUE TITLE
Is there any way I can disable ads on my subscribed channels?

### ISSUE THREAD

**Issue by ShawkMusic** [x0a/uBO-YouTube#11]
This doesn't even seem like it needs any complicated API integration or anything, just check if the Subscribe button is toggled or not when the page loads and turn ads on/off based off that, although I've never programmed a Firefox extension so maybe I'm underestimating it.
Maybe with a blacklist as well so I can set certain subscribed channels to be blocked even with this setting on?

**Comment by x0a** [comment]
Yes actually that first part seems like a rather easy thing to implement, as a "Automatically whitelist subscribed channels" setting (let me know if you have better terminology). Second part is a bit more complicated, requires adding a new blacklist to the settings. Both would have to be implemented at the same time.

But overall sounds like a great idea. Might implement something over this weekend. 

Thanks for the awesome  suggestion

**Comment by x0a** [comment]
[You don't necessarily need to respond to this, just notes for myself]
What we could do is first check to see if the channel is subscribed, then if the 'Automatically whitelist subscribed channels' setting is set to true. If true, check if the channel is blacklisted as a potential whitelist, if it is, don't whitelist. If it's not, whitelist. If the user later re-enables ads (blocks) on the channel, check if it's whitelisted, if it's not, assume it should be blacklisted as a potential whitelist. Maybe display a dialog confirming (would be totally new code).

Hide/show auto-whitelist blacklist depending on whether the setting is enabled.

The 'Import from subscriptions' button would have to include a new clause with something along the lines of 'x channels excluded due to blacklist'.

**Comment by x0a** [comment]
This feature was added as part of https://github.com/x0a/uBO-YouTube/commit/7a92d65ec16eb3b5330fa2e664fba1343fa1fda4

If you are using FF, it should be available immediately. Just update your extensions and head over to https://youtube.com/ubo-yt#misc to enable.

If you are using Chrome, it may be an extra week before they approve the updated extension.

Since this is a new feature that involved some refactoring, feel free to re-open this issue if you encounter any issues so that we can debug further.
