### ISSUE TITLE
Ad Options Persisting Through Video

### ISSUE THREAD

**Issue by Voxtopass** [x0a/uBO-YouTube#2]
![image](https://user-images.githubusercontent.com/30332564/49260452-7d064c00-f3f2-11e8-9a6d-3ffd8402a63b.png)

Hi there. As in the screenshot above, the options that appear over a pre-roll ad persist throughout the entire video, and become unresponsive after the ad ends (either by playing through or by being manually skipped).

Thanks for the great extension, hoping to get this fixed so I can re-enable it.

**Comment by x0a** [comment]
Thanks for the report! 
Are you using the old basic YouTube by any chance? If so it would be a straightforward fix.

**Comment by Voxtopass** [comment]
I am, yes. I didn't even think about that fact.

**Comment by x0a** [comment]
Thanks for confirming, the problem was a missing .hidden CSS rule in the old design.

I've pushed an update to the Chrome and Firefox stores, version 0.7.4 should be available in about 30 minutes.  After that you can just go to your extensions page and tap "Update" to update all your extensions.
Please see if that fixed the problem

**Comment by Voxtopass** [comment]
That worked perfectly. Thank you very much for the quick response. I appreciate your work and you helping support YouTubers!
