### ISSUE TITLE
Unticking auto ad skipping in firefox

### ISSUE THREAD

**Issue by Brissinger** [x0a/uBO-YouTube#20]
Hi.
Every time i open firefox (latest) i have to tick auto skip ads option. Is that intended to be like this?

**Comment by x0a** [comment]
Hey Brissinger,

Thanks for bringing this to my attention. Turns out we weren't properly loading the new settings upon load. Should be fixed in v0.11.7, which will become available in Mozilla Addons any minute now. Reload your extensions and verify that this fixes the problem.

Feel free to re-open this issue if the issue persists (or open a new one if you find anything else).

Thanks
