### ISSUE TITLE
Button not showing up on Youtube

### ISSUE THREAD

**Issue by ricki-k** [x0a/uBO-YouTube#27]
The button that used to appear next to the "Subscribe" button doesn't show up anymore. The extension still works and I can add more channels via the settings page, but the button isn't there.

For what it's worth, [another youtube extension I use that would show the categories for the video I'm currently watching](https://chrome.google.com/webstore/detail/youtube-categories/eddhbfndofdkljemlhkldinjpbkhdpcm) also has stopped working.

Any idea as to how to fix this?

**Comment by x0a** [comment]
Looks like YouTube is officially going all in on the miniplayer. Might take a day or two to fix this.
Thank you for the heads up

[edit] So this may actually take a bit longer than I thought. Channel ID data loading is significantly more inconsistently than before. I may actually need my weekend for this.

**Comment by x0a** [comment]
Should be fixed in v0.13.6 which is now available on both Chrome Web Store and Mozilla Addons. This fixes the missing whitelist button bug but miniplayer support will require a re-write so it will be available in a later version. I'm leaving this bug open until I've verified that all the features are working correctly. 

Thank you again for your report and let me know if you notice any lingering issues. 
<hr />

**Chrome update instructions**

1. Open the Settings menu by clicking **⋮** at the top right
2. Under `More Tools` click on `Extensions`
3. Click on the `Update` button. 

**Firefox update instructions**

1. Open the Settings menu by clicking **≡** at the top right.
2. Click on `Addons`
3. Open the Addons management menu by clicking the **⚙** gear 
4. Click on `Check for updates`. This should update all extensions.

**Comment by azalty** [comment]
Thanks! This fixed it for me on firefox 👍
