### ISSUE TITLE
Unable to mute/block specific advertisers

### ISSUE THREAD

**Issue by DShip91** [x0a/uBO-YouTube#28]
I'm not sure when this changed but when I press on the extension's button on the video player, the options to mute and blacklist that advertiser are grayed out and unselectable. In addition, ads you've seen in general no longer appear in the "Recent ads" section of the options menu.

**Comment by x0a** [comment]
3 days ago YouTube changed the way that ad metadata is loaded. It loads from `/ads?` instead of `/get_video_info?` and is a totally different format and sometimes doesn't include the advertisers channel ID. Should be fixed in a few days.

Thanks for the report

[edit]

I am working on a different method of detecting the current video ID (belonging to the ad) and matching that with the ad metadata provided for the video. It would be ideal if I could use public APIs for this but their API is quota-limited and we've had issues with quota theft in the past so I'm working on a faux-API to gather the necessary information. This is proving a bit more difficult than expected and will take an extra few days.  An update should be released before or on next Monday.

As a reminder if a particular ad is annoying you, you can tap the Right arrow key on your keyboard to auto-skip that ad.

Thank you for your patience so far.

**Comment by x0a** [comment]
Should be fixed in 0.13.9 (available in Mozilla Addons, Chrome Web store has a review process that takes a bit longer).

Due to YouTube changes (video metadata no longer included with ad), detecting the advertiser is now an asynchrous operation that occurs after the video playback details have loaded, meaning there is now a slight delay before your settings kick in (couple hundred milliseconds).

I'm working on changes to hopefully shorten that gap and make ad detection more robust. I'll close the issue once things look good and reliable enough to leave as is. 

Let me know if you encounter any bugs

**Comment by DShip91** [comment]
Thank you.
