### ISSUE TITLE
'Grant' permission button doesn't do anythin in Firefox

### ISSUE THREAD

**Issue by gkgr** [x0a/uBO-YouTube#3]

**Comment by x0a** [comment]
Thanks! I'm able to reproduce this bug in Firefox 65.0b8 and 64.0. 

This seems to be a regression bug with Firefox that we'll have to work around. FF requires a dedicated tab in order to show the permissions request notification, but when it can't find one it doesn't just fail silently, it hangs indefinitely preventing any future permissions requests, even from dedicated tabs.

A suitable workaround would be to remove the "Grant" button from popup.html in Firefox and just link to settings.html

**Comment by x0a** [comment]
Changes in [8854212](https://github.com/x0a/YouTube-Channel-Whitelist-for-uBlock-Origin/commit/8854212b4b83caf19d416e5f720fcbbe39034739) are now available in 0.7.8.

Can you try updating your extensions to verify this solved the problem? Settings > Add-ons > Options cog > Check for updates
"Grant" should now open the dedicated settings page where the actual grant button will be.

**Comment by gkgr** [comment]
Ok, it worked this time. I manually updated the extension and it got to 0.7.9. Just needed a restart Firefox for the update to take effect.
