### ISSUE TITLE
Feature request: Make extension self-documented

### ISSUE THREAD

**Issue by palopezv** [x0a/uBO-YouTube#30]
As it is, if for some reason you have to reset your browser profile and extensions are restored from your cloud backup, you have to start hunting down the magical string needed in uBO's trusted sites list. It would be simple to add a small note in the options screen giving instructions on how to set up the extension. This applies to both the Firefox and Chromium versions.

**Comment by x0a** [comment]
Thank you for your suggestion.

I added a copyable input to Settings > Misc. Changes are available in v0.13.10 which should be on Mozilla Addons soon (Chrome Web store takes a bit longer due to review process).

Once you've updated your extensions, try it [here](http://youtube.com/ubo-yt#misc),

I'm working on a better tooltip system so the fact that the tooltip sometimes goes off-screen will be resolved soon. Let me know if you think this is okay or if you think there might be better placement for the input.

Thanks!

**Comment by x0a** [comment]
Added some tooltip improvements in https://github.com/x0a/uBO-YouTube/commit/58776020262f7321f7d6d8f41d029436c999326f
I'll make it look tidier in the coming days.

Feel free to re-open if you think there is a better placement for the input button.
