### ISSUE TITLE
Feature Request: Add Twitch support

### ISSUE THREAD

**Issue by 10Meisterbaelle** [x0a/uBO-YouTube#32]
Add Twitch support or make a second addon for Twitch

**Comment by x0a** [comment]
Hey,

Thank you for the suggestion. I am strongly considering creating a Twitch version of this addon. It will require a lot of research (and may be technically challenging considering that not even uBO has been able to block ads entirely on Twitch). 
Because of the difficulty (and because it will require a totally different add-on), I can't give an ETA on when/if such an add-on will be available. But once I have a working prototype, I'll leave you a comment letting you know

Thank you
