### ISSUE TITLE
&disableadblock=1 doesn't appear on end video suggestion

### ISSUE THREAD

**Issue by azalty** [x0a/uBO-YouTube#33]
![image](https://user-images.githubusercontent.com/36737524/124361728-dd0ba180-dc30-11eb-9b19-d1f59ea2c366.png)
Url that appears:
![image](https://user-images.githubusercontent.com/36737524/124361753-fca2ca00-dc30-11eb-9c93-dd141c32a92f.png)
instead of https://www.youtube.com/watch?v=L3iJjrQmEho&disableadblock=1

(yes, I enabled ads on this channel)

Thanks for making this addon :)

**Comment by x0a** [comment]
Thank you for the report

Should be pretty easy to fix. I'll have a software update ready by tomorrow.

Thanks again

**Comment by x0a** [comment]
Added some functionality in v0.14.0 to pre-load the channel ID from suggested videos and apply flags accordingly.

Additionally, since YouTube likes to change the link to its default after we've added the flag, we added some code to force the `&disableadblock=1` flag to be re-added to match the built-in adblocker. That should fix this issue and a few other unreported issues

Let me know if you encounter any issues!

Thanks again

<hr>

**Chrome update instructions**

1. Open the Settings menu by clicking **⋮** at the top right
2. Under `More Tools` click on `Extensions`
3. Click on the `Update` button. 

**Firefox update instructions**

1. Open the Settings menu by clicking **≡** at the top right.
2. Click on `Addons`
3. Open the Addons management menu by clicking the **⚙** gear 
4. Click on `Check for updates`. This should update all extensions.
