### ISSUE TITLE
Ads appear on non-whitelisted channels and cause severe lag.

### ISSUE THREAD

**Issue by DShip91** [x0a/uBO-YouTube#36]
For the past week, the extension has been trying to load ads on non-whitelisted channels. This causes Firefox to not know what to do with itself and ends up causing the page to freeze for an extended period of time, all while the ad's progress bar jumps ahead several seconds but the ad doesn't play.

**Comment by x0a** [comment]
Thank you for your report.

That sounds like a pretty serious bug. Is this more likely to happen when you have multiple YouTube tabs open from the same channel? Also do you have 'Whitelist subscribed channels by default' turned on?

On a laggy page, can you hit F12 and post console logs?

Should look like this and can help find evidence of a feedback loop
![Capture](https://user-images.githubusercontent.com/13019784/132630919-fefe2cf0-9c52-42f3-a759-0919fc2df004.PNG)

**Comment by DShip91** [comment]
I would do that but after disabling the add-on for a night and re-enabling it, it seems to be working fine again so it may have just been on my end.

**Comment by DShip91** [comment]
![Screenshot (78)](https://user-images.githubusercontent.com/79122182/132707823-69966cbe-3988-4e76-8b9c-3f6c09cf1ac9.png)

**Comment by DShip91** [comment]
I haven't tried it with multiple YouTube tabs open.

**Comment by x0a** [comment]
Thanks for the screenshot!

It doesn't reveal a feedback loop as would be expected, but this could also be a lack of logging. I've been trying to reproduce the issue with only uBO and uBO-YT and have not been able to reproduce yet. There's a chance that this is a conflict with another extension.

If you can, could you open `about:performance` in another tab and see if there are any other processes consuming large amounts of CPU when the issue occurs? Since uBO-YT uses a userscript, it may not directly reveal that this is the cause of the problem however if its communicating with the background script then it would lead to a high energy impact.


Another way of figuring out where the source of the problem might be would be to pause execution when the page is lagging. To do this, you press F12 and switch to the `Debugging` tab and pause execution using the pause button. (pause button is replaced by play button in my screenshot, because I paused it). It will highlight the last line of code that it was executing. You can  pause/resume execution a couple of times and see if its always lands in roughly the same place.

![Capture](https://user-images.githubusercontent.com/13019784/132803340-ea7da5a4-6577-49da-b586-3971a0907745.PNG)

Post a screenshot if possible.

Thank you

**Comment by DShip91** [comment]
Hey there. The update from two weeks ago seems to have fixed the issue of ads loading on non-whitelisted channels but I'm now having the opposite problem in that I can't get ads to load on videos from whitelisted channels. Any idea what's happening?

**Comment by x0a** [comment]
Thanks for the update! Sorry for the late response. I've been adding additional logging (and logging collection mechanism) to address issues like these a little better.

In the mean time can you try opening logs on a whitelisted channel (where ads are blocked), enable XHR and see if anything is being blocked?

![Capture](https://user-images.githubusercontent.com/13019784/133720360-8291eb5d-c0d0-4572-827c-9008766a46ef.PNG)

If you see `Blocked by Extension` it means that another extension is blocking ads. If you see an event like `22:34:22 uBO-Block JSON-prune: true` and never see a `22:34:22 uBO-Block JSON-prune: false` then that means the extension is not properly turning off internal ad-blocking upon seeing a whitelisted channel. If either of these are the case, then it helps narrow down the source of the issue.

Let me know.

Thanks again

**Comment by DShip91** [comment]
So sorry for taking so long to get back to you on this. Here's a screenshot; I hope it helps.
![Screenshot (93)](https://user-images.githubusercontent.com/79122182/143331031-a22c8f01-2f00-4d80-b4e8-520702f281ef.png)
