### ISSUE TITLE
extension doesn't work in hardened firefox

### ISSUE THREAD

**Issue by ghost** [x0a/uBO-YouTube#37]
Recently reinstalled the add-on into my hardened firefox stable and found that when I click "Options" in the pop out menu I cannot grant permission, change settings. The only things that work in the add-on options page is the "Whitelist > Ads > Misc" header and import/exporting settings (to a certain degree). Importing opens the file picker but shows "Could not set settings, encountered error: Error: Could not establish connection. Receiving end does not exist.". It also appears that the add-on doesn't even inject the add-on's css/buttons on youtube.

**Comment by ghost** [comment]
Forgot to add: I have Container Tabs, Ublock Origin, and ClearUrls. With hardened user.js file.

**Comment by x0a** [comment]
Hey Zachary,

Thank you for your report. Could you navigate to `about:debugging#/runtime/this-firefox`, click `Inspect` next to this extension and post a screenshot of the logs? Feel free to redact any visible subscription/whitelist data.

Also your user.js file could be useful if it has customizations. For reference, I tested with https://github.com/pyllyukko/user.js/ and could not replicate the issue.

Should look like this:

![Capture](https://user-images.githubusercontent.com/13019784/132971569-c9fb1150-d0af-4174-9a20-b41b757a2e0f.PNG)

**Comment by ghost** [comment]
Of course here is the screenshot and my user.js.
![Capture](https://user-images.githubusercontent.com/51203277/132971749-46fadf01-14f8-40d8-8666-3a0e7e74c458.PNG)

user.js - https://hastebin.com/zoxajevuxo.less

**Comment by ghost** [comment]
I noticed that when I click the buttons/switches it spams the "Could not establish connection" message. I have no idea what that means.

**Comment by x0a** [comment]
> I noticed that when I click the buttons/switches it spams the "Could not establish connection" message. I have no idea what that means.

Basically it means that the background script error'd out before it could execute the `addListener` command. So the background script can't respond to any messages sent by any UI or execute any further commands. Thanks to the user.js file I've isolated this to the `user_pref("dom.storage.enabled", false); // Disable DOM storage` in the `user.js` file. 

However I cant test this because something about user.js files prevents me from loading my extension in debugger mode. I'll likely release a fix without testing to test it (ironic) but based on my testing it should work.

**Comment by ghost** [comment]
Awesome, thanks for taking time to debug this issue. Until then I will just use it in Vivaldi (thanks to the native Opera whitelist method). Thanks for making this amazing extension.

**Comment by x0a** [comment]
Thanks again for your patience!

This should now be fixed in v0.14.2, which is now available at Mozilla Addons. Can you check it out and see how well it runs?

<hr>

**Firefox update instructions**

1. Open the Settings menu by clicking **≡** at the top right.
2. Click on `Addons`
3. Open the Addons management menu by clicking the **⚙** gear 
4. Click on `Check for updates`. This should update all extensions.

**Comment by ghost** [comment]
Just updated it now and it works! Something I would like to note for other users, if you have container tabs in Firefox, make sure the extension options page is in the same container tab as YouTube in order for "Import from Subscriptions" to work. Thanks again for fixing this issue.

**Comment by x0a** [comment]
Happy to hear it!
I'll add a note in the README later on.

Feel free to open a new issue if you encounter anything else
