### ISSUE TITLE
Set ads to mute by default

### ISSUE THREAD

**Issue by L-anonyme** [x0a/uBO-YouTube#4]
Hello

Is it possible to put the ads in silent by default and not with each new ad?

**Comment by x0a** [comment]
Yes, I've added a toggle switch to the settings page. To get to the settings page, you can right click the extension icon and click "Options". On Firefox you can just click the extension icon and click the "Settings" button.

On the settings page, next to "Muted advertisers", click "Exempt channels", which will mute ads by default **except** for the items on the list.

![untitled](https://user-images.githubusercontent.com/13019784/52059880-a0ec2800-2530-11e9-8e4a-d3d231ea2de4.png)

Confirmation dialog

![untitled0](https://user-images.githubusercontent.com/13019784/52060421-cb8ab080-2531-11e9-81a0-ee3d444d9e52.png)


Since this is a new feature, feel free to notify me of any issues you encounter.

**Comment by L-anonyme** [comment]
Ah thanks I didn't pay attention to this feature. Sorry
