### ISSUE TITLE
Keyboard Shortcut to Skip Ads

### ISSUE THREAD

**Issue by nixternal** [x0a/uBO-YouTube#43]
Wishlist Item

Add ability to add a keyboard shortcut to fire off the skip ads. Might already be possible, but I haven't figured that out :)

**Comment by x0a** [comment]
Hey,

Thanks for your suggestion. As it turns out, this is already a feature called "Right arrow key to force skip ads" and can be found in Settings > Ads 
Quick link https://youtube.com/ubo-yt#ads


Let me know if this fits your vision for how the feature should work, possible improvements, etc.

Thanks

**Comment by nixternal** [comment]
> Hey,
> 
> Thanks for your suggestion. As it turns out, this is already a feature called "Right arrow key to force skip ads" and can be found in Settings > Ads Quick link https://youtube.com/ubo-yt#ads
> 
> Let me know if this fits your vision for how the feature should work, possible improvements, etc.
> 
> Thanks

Yup, I'm an idiot. I looked there earlier, right before I sent this, and looked right past that. I should be better now, I just cracked a beer. Sorry about this one 🤦🏼‍♂️
