### ISSUE TITLE
Icon usage

### ISSUE THREAD

**Issue by matteioo** [x0a/uBO-YouTube#7]
As you are using Fontawesome for icons but only using max. 5 to 10 from up to thousands of icons it would save disk space if you bundle your needed icons and only save this icons on the computers. There are icon bundler sites which let you do this. For example:

- [IconMoon](https://icomoon.io/app/#/select)

Again, if you are using a CDN for content delivery this isn't really a thought worth as the files won't be saved on the drive. The only dobt then would be that everytime when opening a connection to the cdn, the addon will download all of the CDN related files. If I am wrong in this, please correct me.

Hope my thoughts can help you improving your service 👍

**Comment by x0a** [comment]
Yes of course, I've been wanting to minimize the size of the webfont since it's biggest third party library in the extension.

Just a bit of documentation for myself, no need to respond:

To figure out what icons we're using: `grep -R "fas\?[ -]"`

And classes I use are: 
`fa-minus-circle
far fa-question-circle
fa-file-import
fa-download
fa-trash
fa-cog
fa-link
fa-video-slash
fa-video
fa-volume-mute
fa-ban
fa-search
fa-spinner fa-spin
fa-exclamation-circle
fa-plus
fas-minus`

Not all of these are available at IcoMoon and Fontello unfortunately is still using version 4 whereas we are using version 5. So either I make my own custom webfont, or I switch to FontAwesome-React and be careful about how I import the SVGs. Might take a little while but it should permanently result in a leaner extension which is in line with the uBlock philosophy.

**Comment by x0a** [comment]
By switching to FortAwesome/react-fontawesome, I managed to reduce the final production size from 372KB to 220KB, which represents a little over 40% reduction. Plus this enables us to easily implement some neat FA features later on. Turns out there was no need to worry about carefully importing icons as webpack's [tree shaking](https://fontawesome.com/how-to-use/with-the-api/other/tree-shaking) automatically removed any unused icons.

Thanks!
